import SubpageNavbar from "../_components/subpage-navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <header>
        <SubpageNavbar />
      </header>
      <main className="flex h-full flex-col">
        <div className="flex-1 overflow-auto">{children}</div>
      </main>
    </>
  );
}
